// AUTO-GENERATED by scripts/generate-character-images.mjs — do not edit by hand.
// Add images to assets/characters/<Character>/ and run `npm run images`.
import type { ImageSourcePropType } from "react-native";

export interface CharacterImageSet {
	avatar: ImageSourcePropType;
	backgrounds: readonly ImageSourcePropType[];
}

export const characterImages = {
	"Elle": {
		avatar: require("../../assets/characters/Elle/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Elle/elle-1.jpg"),
		],
	},
	"Garcia": {
		avatar: require("../../assets/characters/Garcia/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Garcia/garcia-1.jpg"),
		],
	},
	"Gideon": {
		avatar: require("../../assets/characters/Gideon/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Gideon/gideon-1.jpg"),
		],
	},
	"Hotch": {
		avatar: require("../../assets/characters/Hotch/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Hotch/hotch-1.jpg"),
		],
	},
	"JJ": {
		avatar: require("../../assets/characters/JJ/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/JJ/jj-1.jpg"),
		],
	},
	"Morgan": {
		avatar: require("../../assets/characters/Morgan/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Morgan/morgan-1.jpg"),
		],
	},
	"Prentiss": {
		avatar: require("../../assets/characters/Prentiss/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Prentiss/prentiss-1.jpg"),
		],
	},
	"Reid": {
		avatar: require("../../assets/characters/Reid/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Reid/reid-1.jpg"),
		],
	},
	"Rossi": {
		avatar: require("../../assets/characters/Rossi/avatar.jpg"),
		backgrounds: [
			require("../../assets/characters/Rossi/rossi-1.jpg"),
		],
	},
} as const satisfies Record<string, CharacterImageSet>;
